lib/better_errors/raised_exception.rb, spec/better_errors/raised_exception_spec.rb
After this update the backtrace will display the correct file with contents.
=> Set backtrace correctly for Coffeelint errors

lib/better_errors/error_page.rb, lib/better_errors/middleware.rb, lib/better_errors/templates/main.erb, lib/better_errors/templates/text.erb, spec/better_errors/error_page_spec.rb
The exception message will now have leading newlines removed to avoid displaying a blank message as a header.
I took the way the error message is constructed from ActiveRecord's MigrationError error class and wrote a test case mimicking it.
Fixes #313
=> Consolidate newlines in exception messages to avoid blank output

README.md
When adding better_errors to a new project I couldn't remember how this was done.
I think this setting would be useful to make more visible.
=> Add section about text editor settings

lib/better_errors/templates/variable_info.erb
We can't show variables without the frame, as stated in the message under the code snippet, so there's no point displaying these sections.
At the moment it just looks like there are no variables.
=> Hide variables unless we have binding_of_caller

Gemfile, spec/better_errors/code_formatter_spec.rb, spec/better_errors/error_page_spec.rb, spec/better_errors/middleware_spec.rb, spec/better_errors/raised_exception_spec.rb, spec/better_errors/repl/pry_spec.rb, spec/better_errors/repl/shared_examples.rb, spec/better_errors/stack_frame_spec.rb, spec/better_errors_spec.rb
As an alternative to #364, we can upgrade to use a newer version of RSpec. This ~should fix~ fixes the build on Travis.
=> Upgrade RSpec

README.md
Currently the readme gives non-optimal instructions for configuring the editor links.
The wiki now has complete instructions, including specifics to install protocol handlers.
Completes #379.
=> Remove partial instructions for editor config

README.md
The readme had an incomplete set of instructions for configuring allow IP addresses. Rather than adding more details to the readme, I moved much of the detail to the wiki page.
Of course, the security warning is intact on the readme, though I tightened the phrasing slightly.
=> Move `allow_ip!` calls to the wiki

README.md
Since using `binding_of_caller` should be used by default, add it to the standard instructions. The note about it being optional is retained.
Also moved the Sinatra installation instructions into the wiki.
=> More clear installation documentation

better_errors.gemspec
Currently we're packaging the test files and all of the screenshot images added for the wiki.
I copied the way that the bundler gem creator does `files`. And I removed `test_files`, since it [seems to be undesirable](https://stackoverflow.com/a/20927191/1589422).
=> Leave extraneous files out of the gem

spec/better_errors/error_page_spec.rb, spec/better_errors/middleware_spec.rb, spec/better_errors/raised_exception_spec.rb
- Remove the last few `should` syntax calls.
- Fix a spec description that was oddly written
=> Spec syntax cleanup

lib/better_errors/middleware.rb, lib/better_errors/templates/main.erb, spec/better_errors/middleware_spec.rb
Currently if the variable fetch fails, it displays a blank area on the page, no indication of failure.
It was parsing the error that came in the response, and placing it in the correct frame, but it wasn't activating the frame so that it was visible. I fixed this.
I then added some more information about the error, including a link to the Better Errors project.
Finally, I added error messages to help those dealing with failures like #301, mostly caused by shotgun or another code-reloading technique. This should give them enough information to have Better Errors working if possible.
If Hanami is in use:
If Middleman is in use:
=> Fix blank frame info area when variable fetch returns error

lib/better_errors/templates/main.erb
Faced the problem when tried to use better errors with hanami. This issue happens only on root path: `http://localhost:3000/` and the reason is that hanami returns rack's `SCRIPT_NAME` equal to pathname:
- `http://example.com/` --> `env["SCRIPT_NAME"] # => "/"`
- `http://example.com/foo` --> `env["SCRIPT_NAME"] # => "/foo"`
- `http://example.com/foo/` --> `env["SCRIPT_NAME"] # => "/foo/"`
=> Fix issue with variable fetch call in Hanami

lib/better_errors/error_page.rb, lib/better_errors/repl/pry.rb
Fixes for newer `pry` versions. Also enables `last_exception` support for calls like `wtf?`.
For reference: https://github.com/charliesome/better_errors/issues/293
Let me know if I can do anything else. Cheers.
=> Fix issues with pry version >= 0.10

better_errors.gemspec, lib/better_errors.rb, lib/better_errors/error_page.rb
Rails has [switched to erubi](https://github.com/rails/rails/pull/27757) for what seem like good reasons: 
- Works with Ruby's `--enable-frozen-string-literal` option
- Has 88% smaller memory footprint
- Does no freedom patching (Erubis adds a method to Kernel)
- Has simpler internals (1 file, <150 lines of code)
- Has an open development model (Erubis doesn't have a public source control repository or bug tracker)
- Is not dead (Erubis hasn't been updated since 2011)
Since Rails has switched, switching the dependency in Better Errors means one fewer dependency for most users. There doesn't seem to be any downside.
This completes #377.
=> Switch from erubis to erubi

lib/better_errors/error_page.rb, lib/better_errors/repl.rb, lib/better_errors/repl/basic.rb, lib/better_errors/repl/pry.rb, spec/better_errors/error_page_spec.rb, spec/better_errors/repl/basic_spec.rb, spec/better_errors/repl/pry_spec.rb
This fixes #393.
The fix in #329 placed some code that was specific to `REPL::Pry` in the `ErrorPage` class. This caused an exception to be raised _when Pry is not enabled_ because `REPL::Pry` class is only loaded after `use_pry!` is called.
To fix this exception, I moved the Pry-specific behavior into `REPL::Pry` and added a new argument to the REPL initializer containing the most recent exception.
(The code was placed in `ErrorPage` because that was the only place where the exception was available at the time.)
I also found that there were no specs covering REPL evaluation, so I added some.
The specs failed until this refactoring was applied.
I then made one further change: since this gem's tests run on Pry 0.9, the use of Pry 0.10+ features (specifically, the use of …
=> Fix Pry `uninitialized constant` exception

README.md, lib/better_errors.rb, lib/better_errors/error_page.rb, spec/better_errors/error_page_spec.rb
Based on my comment on #334 and @tobypinder’s PR #360:
> this will allow the user to set a maximum payload size for `variable.inspect`, above which the variable is filtered out of the error page. This solves many performance problems associated with the browser being slow to render error pages, the CPU requirements for the error page skyrocketing etc.
> 
> Many variable types end up being huge like Rails collections being inspected (and therefore queried for) before they are paginated. I've set the default to 100,000 characters, but the default can be modified to unlimited by setting `BetterErrors.maximum_variable_inspect_size` to `nil`, if we think compatibility is more important than a friendly default.
Closes #360 
Closes #334
=> Fix browser performance issues with configurable maximum variable size

lib/better_errors/templates/main.erb, lib/better_errors/templates/variable_info.erb
If web-console is in the same page as Better Errors, web-console was taking the `.console` element in the page.
This renames it to `.be-console`.
I also renamed the `.prompt` element to `.command-line`, since it wraps the actual prompt and the input element _and_ when it was time to grab the `promptElement` it was looking for the first `span` in it anyway. So things make a little more sense.
Fixes #391.
=> Fix sharing the DOM with web-console

.coveralls.yml, .travis.yml, gemfiles/pry010.gemfile, gemfiles/pry011.gemfile, gemfiles/pry09.gemfile, gemfiles/rack.gemfile, gemfiles/rack_boc.gemfile, gemfiles/rails42.gemfile, gemfiles/rails42_boc.gemfile, gemfiles/rails42_haml.gemfile, gemfiles/rails50.gemfile, gemfiles/rails50_boc.gemfile, gemfiles/rails50_haml.gemfile, gemfiles/rails51.gemfile, gemfiles/rails51_boc.gemfile, gemfiles/rails51_haml.gemfile, spec/spec_helper.rb
Add Coveralls as a development dependency. All CI builds in the main fork (including pull requests) will send coverage data to coveralls.
Each matrix build sends its own coverage data. When all builds have completed, Travis sends a webhook to Coveralls so that it can stitch all coverage data together. This allows us to see which lines are covered by any of the builds. (This project has differing behavior depending on whether Rails of binding_of_caller are included in the bundle, so this is important.)
New pull requests will receive a build status based on whether coverage increased or decreased in that PR.
Ruby 2.4.1 has a bug in its `Coverage` module, so coverage reporting is disabled for that version of Ruby. When 2.4.2 is released, the bug should be fixed, and once the Travis config is …
=> Test coverage reporting in CI

lib/better_errors/templates/variable_info.erb
So that users don't have to find the console prompt with their mouse, they can just hit tab.
=> Make hitting tab key focus on the console

lib/better_errors/middleware.rb
After installed `better_errors` gem in Rails app, the settings in backtrace cleaner won't work in the console. Issue #308 was talked about this.
Tried to introduce Rails BacktraceCleaner if possible.
=> Use Rails BacktraceCleaner to log errors if it's defined

.travis.yml, gemfiles/rails52.gemfile, gemfiles/rails52_boc.gemfile, gemfiles/rails52_haml.gemfile
- Add MRI 2.5.1 (Rails 4.x tests are excluded from this Ruby just like they are from 2.4.x.)
- Remove MRI 2.0.0 and 2.1.10. Since [2.2 is no longer supported](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/) it seems reasonable to remove the previous two releases.
- Update to MRI 2.2.10, 2.3.7, 2.4.4
- Add Rails 5.2
=> Add MRI 2.5 and Rails 5.2 to CI

lib/better_errors.rb, lib/better_errors/error_page.rb, lib/better_errors/inspectable_value.rb, spec/better_errors/error_page_spec.rb
Imported the ObjectSpace library in order to use the memsize_of
when evaluating the size of a variable.
Refs: https://github.com/charliesome/better_errors/issues/412
=> Implemented ObjectSpace.memsize_of in inspect_raw_value

lib/better_errors/stack_frame.rb, spec/better_errors/stack_frame_spec.rb
Some local variables appear to be undefined in the frame_binding.
For example, I see errors on local variables: `m`, `args`, `block`, `r`, and `target` when inspecting an error on a class that inherits from SimpleDelegator.
Fix: Add a rescue on NameError to catch these.
Fixes issue: https://github.com/charliesome/better_errors/issues/351
Inspiration for this fix comes from @glebtv in https://github.com/glebtv/better_errors/commit/6d00365df24eb5660ab32be16728089f7fa1ae13
Example:
=> Rescue on undefined local variables in frame_binding

lib/better_errors.rb, spec/better_errors_spec.rb
According the docs we can call vscode from browser: https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls. 
This PR adds VSCode support.
=> Add support for vscode editor

.travis.yml
Currently CI builds are failing because it's always trying to upgrade rubygems to the latest. The latest version of rubygems refuses to install on ruby <= 2.2.
In addition, the latest version of Bundler refuses to install with an older version of Rubygems, and Rails 4.2 is incompatible with the latest version of Bundler.
Implemented a [suggested fix](https://github.com/rubygems/rubygems/issues/2534) for this so that older Ruby versions will install a version-restricted rubygems and then run it, while newer Ruby versions will continue as before.
=> Fall back to older rubygems on Ruby 2.2 and Rails 4.2

better_errors.gemspec
Without `simplecov` `bundle exec rspec` gives a bunch of errors like:
```
An error occurred while loading ./spec/better_errors/code_formatter_spec.rb.
Failure/Error: require 'simplecov'
LoadError:
cannot load such file -- simplecov
```
=> Adds simplecov as a development dependencie

lib/better_errors/error_page.rb, spec/better_errors/error_page_spec.rb
Avoids the error pointed by https://github.com/BetterErrors/better_errors/issues/411#issuecomment-462005513
When a local/instance variable is anonymous and it's value is too large better_errors prints a default message in https://github.com/BetterErrors/better_errors/blob/master/lib/better_errors/error_page.rb#L111
This pull request adds a fallback to use `obj.class.to_s`, since `obj.class.name` returns nil for anonymous classes causing the following exception:
```
00:23:25 web.1      | Started POST "/admin/__better_errors/50c95030d470e258/variables" for ::1 at 2019-02-09 00:23:25 -0200
00:23:26 web.1      |   
00:23:26 web.1      | TypeError (no implicit conversion of nil into String):
00:23:26 web.1      |   
00:23:26 web.1      | better_errors (2.5.0) …
```
=> Fix exception when large object's class is anonymous

better_errors.gemspec, gemfiles/rails42.gemfile, gemfiles/rails42_boc.gemfile, gemfiles/rails42_haml.gemfile, gemfiles/rails50.gemfile, gemfiles/rails50_boc.gemfile, gemfiles/rails50_haml.gemfile, gemfiles/rails51.gemfile, gemfiles/rails51_boc.gemfile, gemfiles/rails51_haml.gemfile, gemfiles/rails52.gemfile, gemfiles/rails52_boc.gemfile, gemfiles/rails52_haml.gemfile
[CI failure](https://travis-ci.org/BetterErrors/better_errors/builds/493285669) was caused by [kramdown 2.0+ requiring Ruby 2.3+](https://kramdown.gettalong.org/news.html). This fixes it by specifying the older kramdown version when the current Ruby version is older than 2.3.
Same for i18n 1.5.2, which is a dependency of Rails, not a development dependency.
=> Specify older kramdown and i18n for older ruby versions

lib/better_errors/stack_frame.rb
This seems to affect only Jbuilder frames in a Rails 5.1 app. Calling `eval("local_variables")` returns nil in any jbuilder frame. I'm working on a reproducible case for this and a spec to cover it.
```
NoMethodError (undefined method `each_with_object' for nil:NilClass):
better_errors (2.5.0) lib/better_errors/stack_frame.rb:72:in `local_variables'
better_errors (2.5.0) lib/better_errors/error_page.rb:82:in `render'
better_errors (2.5.0) lib/better_errors/error_page.rb:30:in `eval'
better_errors (2.5.0) lib/better_errors/error_page.rb:30:in `render'
better_errors (2.5.0) lib/better_errors/error_page.rb:37:in `do_variables'
better_errors (2.5.0) lib/better_errors/middleware.rb:137:in `internal_call'
better_errors (2.5.0) lib/better_errors/middleware.rb:75:in `better_errors_call' …
```
=> Fix NoMethodError when variables cannot be retrieved from the stack frame

.travis.yml
Update Rubies to latest minor version and exclude Rails 4.2 specs on Ruby 2.3, since the default bundler 2.1.2 gem breaks the downgrade.
Note that I tried to fix this first by using `export BUNDLER_VERSION=1.3`, which works fine locally to prefer Bundler 1.x, even if 2.x is installed, but for some reason that didn't work on Travis CI either.
If we really wanted to we could install bundler 1.17.3 and oveeride the install step to run `bundle _1.17.3_ install …`, but since Rails 4.2 is EOL imho the easiest thing is to just run the 4.2 specs on Ruby 2.2.10.
=> Update CI Ruby to fix Travis CI failures problems

better_errors.gemspec, spec/better_errors/error_page_spec.rb, spec/spec_helper.rb
Many specs for the `ErrorPage` were only looking at whether certain strings appeared in the HTML that was generated. But for different reasons, the string being matched could be included in the generated HTML for other reasons.
For example, if an exception was raised inside of the spec example, the resulting page would be rendered from that exception instead, and it would include lines of code from the exception.
There was some attempt to fix this by breaking up strings in the specs and concatenating them at runtime so that the entire string wasn't in the spec file.
The fix is to use HTML matching and verify that the page contains the correct _tags_ with the content, not just the text.
This failure was exposed by CI failure in #449.
=> Fix various specs that were passing incorrectly

lib/better_errors/raised_exception.rb, spec/better_errors/middleware_spec.rb
Fixes #296. More discussion in #433.
The change here is to not show the most recent exception raised. Previously on Ruby versions supporting `Exception#cause` it would show the most recent exception's cause if there was one.
The behavior in Rails of showing an "original exception" is still in place. This seems to be a desired behavior that's specific to ActionView template errors in Rails before 5.1.
=> Show the last-raised error, not its "cause"

lib/better_errors/raised_exception.rb
When I used better_errors with rails-6.0.2.1 and ruby-2.7.0, I got the following warnings.
```
/Users/yuuu/src/github.com/fusic/mockmock-web/vendor/bundle/ruby/2.7.0/gems/better_errors-2.6.0/lib/better_errors/raised_exception.rb:40: warning: in `eval'
/Users/yuuu/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.2/libexec/bundle:46: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
```
It has been modified to use Binding#source_location with reference to this issue.
https://github.com/pry/pry/issues/2097
=> Fix warning: __FILE__ in eval may not return location in binding

README.md, lib/better_errors.rb, lib/better_errors/error_page.rb, spec/better_errors/error_page_spec.rb
This adds a new global setting `BetterErrors.ignored_classes` that will skip inspecting the value of local and instance variables of this type.
The default setting ignores action dispatch request and response instances, which are usually not printed anyways due to exceeding the limit of `BetterErrors.maximum_variable_inspect_size`, but also avoids
all the memory allocations and database queries that are triggered by calling `#inspect` on variables.
The default setting was chosen to avoid excessive database queries for unloaded relations, because both the `ActionDispatch::Request` and the `ActionDispatch::Response` objects hold many references to the controller instance, causing the same instance variables to be inspected over and over again.
(See https://github.com/rails/rails/pull/38445 …
=> Allow skipping variable inspection by class name

lib/better_errors/raised_exception.rb, spec/better_errors/raised_exception_spec.rb
Fixes #461, fixes #462.
Previous to Rails 5.1, when an error was raised in a template, it included the location within the template in the backtrace. As of 5.1, the exception was replaced with an `ActionView::Template::Error` which provides `file_name` and `line_number` but does not include those in the backtrace.
`SyntaxError` and `Haml::SyntaxError` were handled specially by Better Errors, finding the filename and line number within the exception message and synthesizing a backtrace item based on those. The workaround for `ActionView::Template::Error` looks exactly like those.
The result is that the topmost backtrace item will be the location of the error within the template.
=> Show location of error in ActionView template error

lib/better_errors/error_page.rb, lib/better_errors/templates/main.erb, spec/better_errors/error_page_spec.rb
Fixes #443, fixes #455.
This adds support for actionable exceptions in Rails. For example, when a migration needs to be run it'll offer a button that can run the migrations for the user.
Original Actionable Errors PR in Rails: https://github.com/rails/rails/pull/34788
This is what the original PR uses to create the button:
```htmlerb
<%= button_to action, ActionDispatch::ActionableExceptions.endpoint, params: {
error: exception.class.name,
action: action,
location: request.path
} %>
```
ActionView Helpers aren't loaded in the better errors view, so I instead opted to recreate the form myself using mostly the same variables. It's not a beautiful solution, but it works and I'm not sure if there's really a better way to work around that problem.
The button looks like this:
It's hidden from …
=> Support for Rails ActionableError

README.md, lib/better_errors/templates/variable_info.erb, spec/better_errors/error_page_spec.rb
restrictions for apps running in a third-party iframe
=> Allow editor links to work inside an iframe or with CSP that prohibits other protocols

lib/better_errors/error_page.rb, lib/better_errors/middleware.rb, lib/better_errors/templates/main.erb, spec/better_errors/middleware_spec.rb
Better Errors accepts requests from its own Javascript components in order to provide variables and evaluate console commands. These are now protected by a CSRF token that's set as a cookie when the error page is rendered.
=> Add CSRF protection to internal requests

lib/better_errors/middleware.rb, spec/better_errors/middleware_spec.rb
Internal calls expose exception information which might contain some sensitive information. The method name was taken from the request path and called on the `ErrorPage` instance without validation, which might have led to an insecure situation if a method was added to the `ErrorPage` class without us realizing that it would be exposed through internal calls.
=> Validate internal request method names

lib/better_errors/raised_exception.rb, spec/better_errors/raised_exception_spec.rb
In #459 we stopped always showing the `cause` of an exception. This backs that out a bit by adding a special case for `ActionView::Template::Error` provided by Rails 6. This should solve the incorrect backtrace in that case.
Here's how this came to be:
1. [v0.0.1 of Better Errors](https://github.com/BetterErrors/better_errors/commit/0cb798698268b4c9ab34af580442655ee03a252f) has a special case for `ActionView::Template::Error` to display its `#original_exception` instead of the top-level error.
2. [v0.0.2](https://github.com/BetterErrors/better_errors/commit/a3edf53600c69dea9792edd5cab3d70e9f99a8cc) changes that to follow _any_ `original_exception` regardless of the exception class. I'm not sure why this was done, but likely it's because there are errors similar to …
=> Show real cause of ActionView::Template::Error with Rails 6

lib/better_errors/middleware.rb
Fixes #476.
Since the initial Better Errors console can be opened on any path, the CSRF cookie might be set initially within a path. This would limit the visibility of the cookie, causing subsequent requests to internal Better Errors calls (which are are at `/__better_errors`) to fail because the cookie is not available in the request.
This fixes the issue by setting the CSRF Token cookie in the root path, which will make it available to all internal Better Errors requests as well as any console that will open as the result of an error thrown within the application.
In order to reduce any problems caused by CSRF tokens set with a limited path by an older version of Better Errors, the BE version is now also part of the CSRF Token cookie name. While the cookie would expire at the end of the …
=> Fix path of CSRF Token cookie

lib/better_errors/middleware.rb
Due to the changes with CSRF_TOKEN_COOKIE_NAME, when using Better Errors version 2.8.2 I would get the following error:
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant': uninitialized constant BetterErrors::Middleware::VERSION (NameError) 56: from ~/Documents/MyProject/bin/rails:3:in `<main>
(Stack trace shorten for readability)
Downgrading to version 2.8.1 fixed the error. I believe the issue is that there is no constant named VERSION in the Middleware class, so the version number from the BetterErrors module should be used instead.
=> Fixed 'uninitialized constant BetterErrors::Middleware::VERSION' in version 2.8.2

lib/better_errors.rb, lib/better_errors/middleware.rb
It might relate to discussion at https://github.com/BetterErrors/better_errors/issues/479
After upgrading to `2.8.2` I started experiencing the following error:
```ruby
11:58:02 rails.1   | /Users/my-user/.rvm/gems/ruby-2.6.6/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:43:in `<class:Middleware>‘: uninitialized constant BetterErrors::Middleware::VERSION (NameError)
11:58:02 rails.1   | 	from /Users/my-user/.rvm/gems/ruby-2.6.6/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:28:in `<module:BetterErrors>'
11:58:02 rails.1   | 	from /Users/my-user/.rvm/gems/ruby-2.6.6/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:7:in `<top (required)>'
11:58:02 rails.1   | 	from /Users/my-user/.rvm/gems/ruby-2.6.6/gems/better_errors-2.8.2/lib/better_errors.rb:9:in `<top …
```
=> Fix CSRF_TOKEN_COOKIE_NAME wrong reference to VERSION constant

lib/better_errors/templates/text.erb, spec/better_errors/middleware_spec.rb
Add a simple note to the text error response that points the developer at the `/__better_errors` path so they can interact with the console.
Fixes #486
=> Mention path in text response

lib/better_errors/raised_exception.rb, lib/better_errors/templates/main.erb, spec/better_errors/raised_exception_spec.rb
I work with a lot of people who are new to coding, and have found that people often get tripped up with reading Ruby exceptions. For example:
``` ruby
user = User.where(...).first
user # => nil
user.save # NoMethodError: undefined method `save' for nil:NilClass
```
While precise, error messages like this don't do a very good job of guiding the reader to how to fix the problems. This PR is a proof-of-concept giving better_errors users a bit of help.
Feedback welcome! In particular, what edge cases am I missing?
**P.S.** Ideally the message above would read
> Hint: `user` is `nil` when it probably shouldn't be.
but that requires some fancy AST parsing (I think).
**P.P.S.** If others agree it would be useful, I think a good medium-term goal would be to move the backtrace cleaning and hint …
=> add exception hints

lib/better_errors/templates/main.erb, lib/better_errors/templates/variable_info.erb
This is an implementation of the request in #315, but instead of removing the hint completely, it's shown only when the console has never been used.
The JS on the page sets a cookie when the user types in the console, and hides the hint if that cookie is present. (The cookie will expire after one year.)
Closes #342
Fixes #315
=> Hide "live shell" hint after console has been used

lib/better_errors.rb, lib/better_errors/editor.rb, lib/better_errors/error_page.rb, spec/better_errors/editor_spec.rb, spec/better_errors_spec.rb, spec/spec_helper.rb
This refactors editor detection out of the `BetterErrors` class into a new `Editor` class, while preserving the call pattern on `BetterErrors.editor=`.
=> Improve editor support for virtual environments

lib/better_errors/templates/main.erb, lib/better_errors/templates/variable_info.erb
Fixes the work just merged in #490. The hint was reappearing when the user clicked a different frame.
This logic didn't belong inside of the `REPL` prototype anyway, so moving it out of there. Using CSS to hide it, we only need to add a body class at startup, or later, but only once.
=> Fix "live shell" hint reappearing when frame changed

lib/better_errors.rb, spec/better_errors_spec.rb
The changes in commit 6591cf998872940ae64086444aa59be30f1cbe9c broke setting an editor with a symbol, when the method `Editor.for_symbol` was renamed to `Editor.editor_from_symbol`.
=> Fix setting editor with symbol

.github/workflows/ci.yml, gemfiles/rails61.gemfile, gemfiles/rails61_boc.gemfile, gemfiles/rails61_haml.gemfile
[6.1.0rc1](https://weblog.rubyonrails.org/2020/11/2/Rails-6-1-rc1-release/) is out, so let's make sure we remain compatible.
=> Add Rails 6.1 to CI matrix

lib/better_errors/editor.rb, lib/better_errors/error_page.rb, lib/better_errors/middleware.rb, lib/better_errors/templates/main.erb, lib/better_errors/templates/text.erb, lib/better_errors/templates/variable_info.erb, spec/better_errors/error_page_spec.rb
Add our own Content Security Policy headers when Better Errors responds, which heavily restricts the resources that can be used/referenced, but allows our scripts and styles. It uses a nonce for the script blocks, but currently we rely on inline style because of the way syntax highlighting works (which will change someday, for example in #423).
When Turbolinks is in use, our headers are not evaluated by the browser when loading the console page. If the CSP headers sent by the application restrict inline CSS and JS, the console will not function or be presented correctly.
So we also provide fallback modes, where the user is informed of the reason and given a link to open Better Errors in a new tab. This fallback includes the topmost frame infomation, so essentially the same information as …
=> Add Content Security Policy

Rakefile, lib/better_errors/code_formatter.rb, lib/better_errors/code_formatter/html.rb, lib/better_errors/error_page_style.rb, lib/better_errors/middleware.rb, lib/better_errors/style/main.scss, lib/better_errors/style/syntax_highlighting.scss, lib/better_errors/templates/main.erb
- Use CSS classes to provide code syntax highlighting style.
- That gets rid of the last use of `style` attributes, so add a nonce to the style tag and lock down the `style-src` Content Security Policy.
- Also fix the attempted load of a favicon. We never referred to one in Better Erors, but the browser attempts to load `/favicon.ico` by default. So by providing a blank one and allowing `data:` img-src in the CSP, we can stop the browser from complaining about it. (It might be nice to actually have a favicon representing Better Errors, but it doesn't seem very important right now.)
=> Syntax highlighter uses classes, style-src locked down

lib/better_errors/error_page_style.rb
This change moves the `require` call to only be invoked the first time that the Sass files are compiled. This solves the issue of applications that don't use Sass loading `better_errors` without needing to install `sassc` (see https://github.com/BetterErrors/better_errors/issues/516), and is an alternative resolution to https://github.com/BetterErrors/better_errors/pull/515.
Note: Some specs are failing for me that seem unrelated to this change, and are present even when running specs on the unmodified `master` branch. I'm not seeing tests running in CI, so a maintainer may need to verify that this fix actually works as intended.
=> Require sassc only in development
